// This causes me pure pain
const TileImages: string[][] = [];

import tile_0 from "../assets/images/tiles/tile_0.svg";
import tile_1 from "../assets/images/tiles/tile_1.svg";
import tile_2 from "../assets/images/tiles/tile_2.svg";
import tile_3 from "../assets/images/tiles/tile_3.svg";
import tile_4 from "../assets/images/tiles/tile_4.svg";
import tile_4_red from "../assets/images/tiles/tile_4_red.svg";
import tile_5 from "../assets/images/tiles/tile_5.svg";
import tile_6 from "../assets/images/tiles/tile_6.svg";
import tile_7 from "../assets/images/tiles/tile_7.svg";
import tile_8 from "../assets/images/tiles/tile_8.svg";
import tile_9 from "../assets/images/tiles/tile_9.svg";
import tile_10 from "../assets/images/tiles/tile_10.svg";
import tile_11 from "../assets/images/tiles/tile_11.svg";
import tile_12 from "../assets/images/tiles/tile_12.svg";
import tile_13 from "../assets/images/tiles/tile_13.svg";
import tile_13_red from "../assets/images/tiles/tile_13_red.svg";
import tile_14 from "../assets/images/tiles/tile_14.svg";
import tile_15 from "../assets/images/tiles/tile_15.svg";
import tile_16 from "../assets/images/tiles/tile_16.svg";
import tile_17 from "../assets/images/tiles/tile_17.svg";
import tile_18 from "../assets/images/tiles/tile_18.svg";
import tile_19 from "../assets/images/tiles/tile_19.svg";
import tile_20 from "../assets/images/tiles/tile_20.svg";
import tile_21 from "../assets/images/tiles/tile_21.svg";
import tile_22 from "../assets/images/tiles/tile_22.svg";
import tile_22_red from "../assets/images/tiles/tile_22_red.svg";
import tile_23 from "../assets/images/tiles/tile_23.svg";
import tile_24 from "../assets/images/tiles/tile_24.svg";
import tile_25 from "../assets/images/tiles/tile_25.svg";
import tile_26 from "../assets/images/tiles/tile_26.svg";
import tile_27 from "../assets/images/tiles/tile_27.svg";
import tile_28 from "../assets/images/tiles/tile_28.svg";
import tile_29 from "../assets/images/tiles/tile_29.svg";
import tile_30 from "../assets/images/tiles/tile_30.svg";
import tile_31 from "../assets/images/tiles/tile_31.svg";
import tile_32 from "../assets/images/tiles/tile_32.svg";
import tile_33 from "../assets/images/tiles/tile_33.svg";

TileImages.push([tile_0]);
TileImages.push([tile_1]);
TileImages.push([tile_2]);
TileImages.push([tile_3]);
TileImages.push([tile_4, tile_4_red]);
TileImages.push([tile_5]);
TileImages.push([tile_6]);
TileImages.push([tile_7]);
TileImages.push([tile_8]);
TileImages.push([tile_9]);
TileImages.push([tile_10]);
TileImages.push([tile_11]);
TileImages.push([tile_12]);
TileImages.push([tile_13, tile_13_red]);
TileImages.push([tile_14]);
TileImages.push([tile_15]);
TileImages.push([tile_16]);
TileImages.push([tile_17]);
TileImages.push([tile_18]);
TileImages.push([tile_19]);
TileImages.push([tile_20]);
TileImages.push([tile_21]);
TileImages.push([tile_22, tile_22_red]);
TileImages.push([tile_23]);
TileImages.push([tile_24]);
TileImages.push([tile_25]);
TileImages.push([tile_26]);
TileImages.push([tile_27]);
TileImages.push([tile_28]);
TileImages.push([tile_29]);
TileImages.push([tile_30]);
TileImages.push([tile_31]);
TileImages.push([tile_32]);
TileImages.push([tile_33]);

export default TileImages;
