// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateScore(arg1:string,arg2:main.Conditions,arg3:number):Promise<main.Score>;

export function CalculateWaits(arg1:string):Promise<Array<main.Tile>>;
