// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateScore(arg1, arg2, arg3) {
  return window['go']['main']['Calculator']['CalculateScore'](arg1, arg2, arg3);
}

export function CalculateWaits(arg1) {
  return window['go']['main']['Calculator']['CalculateWaits'](arg1);
}
